### ISSUE TITLE
error in pycom.py setup command: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by SantiagoRestrepoRuizFourier** [Omyyyy/pycom#9]
I'm facing this problem on Windows:

when running the command:
pip install -e .

I get:

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in pycom.py setup command: 'NoneType' object has no attribute 'group'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by riebecj** [comment]
Oh, dang! I added `/`'s instead of `.`'s in the `setup.py`.

**Comment by riebecj** [comment]
It is fixed:

```bash
caseyrb@Casey-PC:~/DevBox/pycom$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/caseyrb/DevBox/pycom
  Preparing metadata (setup.py) ... done
Installing collected packages: pycom.py
  Running setup.py develop for pycom.py
Successfully installed pycom.py-1.0.0
```
